platform :ios, ‘9.0’

target “MapDemo” do
    
pod 'AFNetworking'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'MJExtension'
pod 'Masonry'
pod 'SDCycleScrollView'
pod 'DGActivityIndicatorView'
pod 'HMSegmentedControl'
pod 'Toast'
pod 'JKCountDownButton'
pod 'BRPickerView'
pod 'QMUIKit', '~> 4.0.0-beta'
pod 'AMap3DMap'
pod 'AMapLocation'
pod 'AMapSearch'
pod 'AMapNavi'

end
